Corrected import and added IP on which to listen to devel server.
fergalwalsh/pico pull request #21
Opened 2020-03-22 14:03 UTC by rbeneyt

2020-03-26 23:00 UTC, fergalwalsh requested changes
Thanks for the fix and enhancement. Both issues bothered me recently but I didn't get around to fixing them. See the inline comments for some suggested edits.

2020-03-27 10:55 UTC, rbeneyt commented on pico/server.py
> +    run_app(app, server_ip)
Hi Fergal, yep that's better. I'll ad the port in another request.

2020-03-27 12:06 UTC, rbeneyt commented on pico/server.py
> +#from werkzeug.wsgi import SharedDataMiddleware
Ok, I'm not sure about how to do it, first time using github, so I'll submit another pull request with all the changes.

2020-03-27 12:21 UTC, rbeneyt commented on pico/server.py
> +#from werkzeug.wsgi import SharedDataMiddleware
Added 2 commits with the changes, below.

2020-03-27 13:26 UTC, fergalwalsh approved these changes
That's great. Thank you.

2020-03-27 13:27 UTC, fergalwalsh commented
Congrats on your first PR 🎉

2020-03-27 13:27 UTC, merged

2020-03-27 13:31 UTC, fergalwalsh commented
FYI this is merged to master but I have not yet pushed a new release to PyPI. In the meantime you can install it directly from git using `pip install git+https://github.com/fergalwalsh/pico.git@master`

2020-03-29 06:00 UTC, StefanoSega commented
@fergalwalsh  it doesn't work for me with Werkzeug 0.14.1, it works btw with Werkzeug 0.16.1

2020-04-01 12:11 UTC, fergalwalsh commented
Thanks @StefanoSega, I have bumped the requirement now. It is in the master branch.